/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MecanicienDto } from '../../models/mecanicien-dto';

export interface AddNotation$Params {
  id?: number;
      body: number
}

export function addNotation(http: HttpClient, rootUrl: string, params: AddNotation$Params, context?: HttpContext): Observable<StrictHttpResponse<MecanicienDto>> {
  const rb = new RequestBuilder(rootUrl, addNotation.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MecanicienDto>;
    })
  );
}

addNotation.PATH = '/automobiliste/Mecanicien/AddNotation/{id}';
